spring:
   application:
      name: Customer
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/customer_db?useSSL=false
      username: postgres
      password: pass
   jpa:
      show-sql: true
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         ddl-auto: create
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
   main:
      allow-bean-definition-overriding: true
   zipkin:
      base-url: http://${zipkin-service_SERVICE_HOST}:${zipkin-service_SERVICE_PORT}/
      
server:
   port: 9001
   
logging:
   level:
      root: WARN
      com:
         murali:
            customer: DEBUG
   