spring:
   application:
      name: Product
   main:
      allow-bean-definition-overriding: true
   zipkin:
      base-url: http://${zipkin-service_SERVICE_HOST}:${zipkin-service_SERVICE_PORT}/
      
server:
   port: 9004
   
logging:
   level:
      root: WARN
      com:
         murali:
            product: DEBUG  
   