spring:
   application:
      name: Payment
   main:
      allow-bean-definition-overriding: true
   zipkin:
      base-url: http://${zipkin-service_SERVICE_HOST}:${zipkin-service_SERVICE_PORT}/
      
server:
   port: 9003
   
logging:
   level:
      root: WARN
      com:
         murali:
            payment: DEBUG  
   